# Example Cloud Run service configuration for Consensus Engine API Backend
#
# This file demonstrates how to deploy the FastAPI backend as a Cloud Run service
# with IAM-based authentication (no public access without valid credentials).
#
# Usage:
#   1. Replace placeholders with your actual values
#   2. Deploy: gcloud run services replace backend-service.yaml
#   3. Grant IAM roles to service accounts that need access:
#      - Frontend service account needs roles/run.invoker
#      - Worker service account needs roles/run.invoker (if calling API)
#
# Note: This is an example configuration. Adjust resource limits, scaling, and
# environment variables based on your actual requirements.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consensus-api
  namespace: 'PROJECT_ID'  # Replace with your GCP project ID
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/ingress-status: internal-and-cloud-load-balancing
spec:
  template:
    metadata:
      annotations:
        # Scaling configuration
        autoscaling.knative.dev/minScale: '1'  # Keep at least 1 instance warm
        autoscaling.knative.dev/maxScale: '20'
        
        # CPU allocation (always allocated for API responsiveness)
        run.googleapis.com/cpu-throttling: 'false'
        
        # Execution environment (Second generation recommended)
        run.googleapis.com/execution-environment: gen2
        
        # Cloud SQL connection (if using Cloud SQL)
        run.googleapis.com/cloudsql-instances: 'PROJECT_ID:REGION:INSTANCE_NAME'
        
        # VPC connector (if needed for VPC access)
        # run.googleapis.com/vpc-access-connector: 'projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME'
        # run.googleapis.com/vpc-access-egress: 'private-ranges-only'
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: 'consensus-api-sa@PROJECT_ID.iam.gserviceaccount.com'  # Replace
      containers:
      - name: consensus-api
        image: 'gcr.io/PROJECT_ID/consensus-api:latest'  # Replace with your image
        ports:
        - name: http1
          containerPort: 8000
        env:
        # OpenAI Configuration
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        - name: OPENAI_MODEL
          value: 'gpt-5.1'
        - name: TEMPERATURE
          value: '0.7'
        - name: EXPAND_MODEL
          value: 'gpt-5.1'
        - name: EXPAND_TEMPERATURE
          value: '0.7'
        - name: REVIEW_MODEL
          value: 'gpt-5.1'
        - name: REVIEW_TEMPERATURE
          value: '0.2'
        - name: AGGREGATE_MODEL
          value: 'gpt-5.1'
        - name: AGGREGATE_TEMPERATURE
          value: '0.0'
        
        # Environment
        - name: ENV
          value: 'production'
        
        # CORS Configuration
        - name: CORS_ORIGINS
          value: 'https://consensus-web-HASH-uc.a.run.app'  # Replace with frontend URL
        - name: CORS_ALLOW_HEADERS
          value: 'Content-Type,Authorization,X-Request-ID,X-Schema-Version,X-Prompt-Set-Version'
        
        # Database Configuration (Cloud SQL)
        - name: USE_CLOUD_SQL_CONNECTOR
          value: 'true'
        - name: DB_INSTANCE_CONNECTION_NAME
          value: 'PROJECT_ID:REGION:INSTANCE_NAME'  # Replace
        - name: DB_NAME
          value: 'consensus_engine'
        - name: DB_USER
          value: 'consensus-api-sa@PROJECT_ID.iam'  # IAM user
        - name: DB_IAM_AUTH
          value: 'true'
        - name: DB_POOL_SIZE
          value: '5'
        - name: DB_MAX_OVERFLOW
          value: '10'
        - name: DB_POOL_TIMEOUT
          value: '30'
        - name: DB_POOL_RECYCLE
          value: '3600'
        
        # Pub/Sub Configuration
        - name: PUBSUB_PROJECT_ID
          value: 'PROJECT_ID'  # Replace
        - name: PUBSUB_TOPIC
          value: 'consensus-engine-jobs'
        - name: PUBSUB_SUBSCRIPTION
          value: 'consensus-engine-jobs-sub'
        
        # Worker Configuration
        - name: WORKER_MAX_CONCURRENCY
          value: '10'
        - name: WORKER_ACK_DEADLINE_SECONDS
          value: '600'
        - name: WORKER_STEP_TIMEOUT_SECONDS
          value: '300'
        - name: WORKER_JOB_TIMEOUT_SECONDS
          value: '1800'
        
        # API Validation Configuration
        - name: MAX_IDEA_LENGTH
          value: '10000'
        - name: MAX_EXTRA_CONTEXT_LENGTH
          value: '50000'
        - name: MAX_EDITED_PROPOSAL_LENGTH
          value: '100000'
        - name: MAX_EDIT_NOTES_LENGTH
          value: '10000'
        
        resources:
          limits:
            cpu: '2000m'
            memory: '2Gi'
        
        # Health check
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12  # Allow up to 60 seconds for startup
  
  traffic:
  - percent: 100
    latestRevision: true
